version: '3.8'

services:
  php:
    build: .
    container_name: php-container
    ports:
      - "80:80"  # Map host port 80 to container port 80
    depends_on:
      - db
    networks:
      - php-mysql-network

  db:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: example_db
      MYSQL_USER: phpuser
      MYSQL_PASSWORD: phppassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - php-mysql-network

volumes:
  mysql_data:

networks:
  php-mysql-network:
    driver: bridge
