services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: u499940289_sitara
      MYSQL_USER: u499940289_SiTaRa
      MYSQL_PASSWORD: Sitara@123
    volumes:
      - db_data:/var/lib/mysql
      - ./Wordpress/u499940289_sitara.sql:/docker-entrypoint-initdb.d/u499940289_sitara.sql

  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./Wordpress:/var/www/html
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: u499940289_sitara
      MYSQL_USER: u499940289_SiTaRa
      MYSQL_PASSWORD: Sitara@123
volumes:
  db_data:
